///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace project_2.mailcare
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The get_mail recording.
    /// </summary>
    [TestModule("c8fbed59-2353-4609-aeb6-03e3d63d3b45", ModuleType.Recording, 1)]
    public partial class get_mail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::project_2.Repository repository.
        /// </summary>
        public static global::project_2.Repository repo = global::project_2.Repository.Instance;

        static get_mail instance = new get_mail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public get_mail()
        {
            response = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static get_mail Instance
        {
            get { return instance; }
        }

#region Variables

        string _response;

        /// <summary>
        /// Gets or sets the value of variable response.
        /// </summary>
        [TestVariable("28115e79-00bc-42a3-8537-967298df2dfd")]
        public string response
        {
            get { return _response; }
            set { _response = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
