///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Calculator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CalculatorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("abad8696-c8e5-4f44-ad5c-fb89e3d58021")]
    public partial class CalculatorRepository : RepoGenBaseFolder
    {
        static CalculatorRepository instance = new CalculatorRepository();
        CalculatorRepositoryFolders.RechnerAppFolder _rechner;

        /// <summary>
        /// Gets the singleton class instance representing the CalculatorRepository element repository.
        /// </summary>
        [RepositoryFolder("abad8696-c8e5-4f44-ad5c-fb89e3d58021")]
        public static CalculatorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CalculatorRepository() 
            : base("CalculatorRepository", "/", null, 0, false, "abad8696-c8e5-4f44-ad5c-fb89e3d58021", ".\\RepositoryImages\\CalculatorRepositoryabad8696.rximgres")
        {
            _rechner = new CalculatorRepositoryFolders.RechnerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("abad8696-c8e5-4f44-ad5c-fb89e3d58021")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Rechner folder.
        /// </summary>
        [RepositoryFolder("91468a57-2628-4c33-91bb-17e304f46de0")]
        public virtual CalculatorRepositoryFolders.RechnerAppFolder Rechner
        {
            get { return _rechner; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CalculatorRepositoryFolders
    {
        /// <summary>
        /// The RechnerAppFolder folder.
        /// </summary>
        [RepositoryFolder("91468a57-2628-4c33-91bb-17e304f46de0")]
        public partial class RechnerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Rechner  folder.
            /// </summary>
            public RechnerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Rechner", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "91468a57-2628-4c33-91bb-17e304f46de0", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@automationid='Close']", 30000, null, "543f7e26-4173-43f7-85dc-180abca582c6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("91468a57-2628-4c33-91bb-17e304f46de0")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("91468a57-2628-4c33-91bb-17e304f46de0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("543f7e26-4173-43f7-85dc-180abca582c6")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("543f7e26-4173-43f7-85dc-180abca582c6")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
