///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace project_2.lab
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ini_read_write recording.
    /// </summary>
    [TestModule("f8645906-f5d3-42da-8927-a4593c182542", ModuleType.Recording, 1)]
    public partial class ini_read_write : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::project_2.Repository repository.
        /// </summary>
        public static global::project_2.Repository repo = global::project_2.Repository.Instance;

        static ini_read_write instance = new ini_read_write();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ini_read_write()
        {
            ini_file = "";
            section = "";
            key = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ini_read_write Instance
        {
            get { return instance; }
        }

#region Variables

        string _ini_file;

        /// <summary>
        /// Gets or sets the value of variable ini_file.
        /// </summary>
        [TestVariable("615be89d-b7a3-4af0-a7c0-ccaaff175d1d")]
        public string ini_file
        {
            get { return _ini_file; }
            set { _ini_file = value; }
        }

        string _section;

        /// <summary>
        /// Gets or sets the value of variable section.
        /// </summary>
        [TestVariable("41dafecc-e7fa-4630-bf9c-7aa97d72c684")]
        public string section
        {
            get { return _section; }
            set { _section = value; }
        }

        string _key;

        /// <summary>
        /// Gets or sets the value of variable key.
        /// </summary>
        [TestVariable("b9eb80b3-8982-4eb9-ac38-749def9ca2b1")]
        public string key
        {
            get { return _key; }
            set { _key = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            read();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
