///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

using System.IO;
using System.Windows.Forms;

using IniParser;
using IniParser.Model;

namespace project_2.lab
{
	public partial class ini_read_write
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

		public void read()
		{


			string appPath = Path.GetDirectoryName(Application.ExecutablePath);
			Ranorex.Report.Info("exe path: " + appPath);	
			string ini_file = Path.Combine(appPath, @"resources\server.ini");
			var parser = new FileIniDataParser();
			IniData data = parser.ReadFile(ini_file);
			string str_5545 = data["Common"]["5545"];
			Ranorex.Report.Info("5545: " + str_5545 );
			
			data["Common"]["5545"] = "hello";
			parser.WriteFile(ini_file, data);
			
		}

	}
}
