///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace project_2.lab
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The psexec_handler recording.
    /// </summary>
    [TestModule("274359b7-cb35-4f2e-a4e0-b0a2f8b8eea4", ModuleType.Recording, 1)]
    public partial class psexec_handler : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::project_2.Repository repository.
        /// </summary>
        public static global::project_2.Repository repo = global::project_2.Repository.Instance;

        static psexec_handler instance = new psexec_handler();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public psexec_handler()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static psexec_handler Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //get_cmd_remote("vagrant-1", "vagrant", "vagrant", "", "Get-WMIObject –Class Win32_Bios | Select PSComputername, __Server");
            //Delay.Milliseconds(0);
            
            //psexec_2();
            //Delay.Milliseconds(0);
            
            psexec_3();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
