///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace global_repo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the global_repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e8abadf6-fac5-414e-bd6b-9fe377c28278")]
    public partial class global_repo : RepoGenBaseFolder
    {
        static global_repo instance = new global_repo();
        global_repoFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the global_repo element repository.
        /// </summary>
        [RepositoryFolder("e8abadf6-fac5-414e-bd6b-9fe377c28278")]
        public static global_repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public global_repo() 
            : base("global_repo", "/", null, 0, false, "e8abadf6-fac5-414e-bd6b-9fe377c28278", ".\\RepositoryImages\\global_repoe8abadf6.rximgres")
        {
            _explorer = new global_repoFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e8abadf6-fac5-414e-bd6b-9fe377c28278")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("f57b2f6f-4012-450d-9660-de353ba14274")]
        public virtual global_repoFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class global_repoFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("f57b2f6f-4012-450d-9660-de353ba14274")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _microsoftedgeInfo;
            RepoItemInfo _fileexplorerInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "f57b2f6f-4012-450d-9660-de353ba14274", "")
            {
                _microsoftedgeInfo = new RepoItemInfo(this, "MicrosoftEdge", "form[@controlid='40965']", 30000, null, "e0d5b68a-ce5f-4921-b7c2-507f1a0e5fa9");
                _fileexplorerInfo = new RepoItemInfo(this, "FileExplorer", "form[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename='File Explorer']", 30000, null, "f180434a-15fb-4fc6-80b8-2611763d08d3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f57b2f6f-4012-450d-9660-de353ba14274")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f57b2f6f-4012-450d-9660-de353ba14274")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MicrosoftEdge item.
            /// </summary>
            [RepositoryItem("e0d5b68a-ce5f-4921-b7c2-507f1a0e5fa9")]
            public virtual Ranorex.Form MicrosoftEdge
            {
                get
                {
                    return _microsoftedgeInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The MicrosoftEdge item info.
            /// </summary>
            [RepositoryItemInfo("e0d5b68a-ce5f-4921-b7c2-507f1a0e5fa9")]
            public virtual RepoItemInfo MicrosoftEdgeInfo
            {
                get
                {
                    return _microsoftedgeInfo;
                }
            }

            /// <summary>
            /// The FileExplorer item.
            /// </summary>
            [RepositoryItem("f180434a-15fb-4fc6-80b8-2611763d08d3")]
            public virtual Ranorex.Button FileExplorer
            {
                get
                {
                    return _fileexplorerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FileExplorer item info.
            /// </summary>
            [RepositoryItemInfo("f180434a-15fb-4fc6-80b8-2611763d08d3")]
            public virtual RepoItemInfo FileExplorerInfo
            {
                get
                {
                    return _fileexplorerInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
