///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

using System.IO;
using System.Diagnostics;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json; //nuget package
using System.Net.Http;
using System.Web;
using System.Net;
using System.Net.Mail;

namespace project_2.mailsac
{
	public partial class get_mailsac_mail
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

		public void get_mail()
		{
			Ranorex.Report.Info("get mail");
			//HttpWebRequest request = (HttpWebRequest)WebRequest.Create("https://mailsac.com/api/text/vdog%40mailsac.com/8ca5La9MPJGIRDjQ-hSrWjg-0");
			HttpWebRequest request = (HttpWebRequest)WebRequest.Create("https://mailsac.com/api/addresses/vdog%40mailsac.com/messages/8ca5La9MPJGIRDjQ-hSrWjg-0");
			request.Method = "GET";
			request.ContentType = "application/json";
			//request.ContentLength = DATA.Length;
			//StreamWriter requestWriter = new StreamWriter(request.GetRequestStream(), System.Text.Encoding.ASCII);
			//requestWriter.Write(DATA);
			//requestWriter.Close();

			try {
				WebResponse webResponse = request.GetResponse();
				Stream webStream = webResponse.GetResponseStream();
				//StreamReader responseReader = new StreamReader(webStream, Encoding.ASCII);
				StreamReader responseReader = new StreamReader(webStream);
				string response = responseReader.ReadToEnd();
				Ranorex.Report.Info(response);
				
				//	JObject studentObj = JObject.Parse(response);
				/*
				JArray jarray = JArray.Parse(response);
				foreach(var item in jarray.Children())
				{
					var x = item.First;
				}
				*/
				//	var id = jarray["_id"][0];
				//	Ranorex.Report.Info("id: " + id.ToString());

				
				responseReader.Close();
			} catch (Exception e) {
				Ranorex.Report.Info("-----------------");
				Ranorex.Report.Info(e.Message);
			}
		}

	}
}
