///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

using Newtonsoft.Json;

namespace project_2
{
    public partial class parse_string_to_json
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void parse()
        {
        	//string source = @"{"mailItems":[{"id":"283f7daa-e56d-47b2-60e0-8659fe78f2c1","dateSent":"2020-02-22 13:55:42","fromAddress":"from@test.de","toAddresses":["test@test.de"],"subject":"slurpermail","xmailer":"","mimeVersion":"","body":"This is for testing SMTP mail from GMAIL\n\u003cbr/\u003e\n\u003cbr/\u003e","contentType":"text/plain; charset=us-ascii","boundary":"","attachments":[],"transferEncoding":"","Message":null,"InlineAttachments":null,"TextBody":"","HTMLBody":""}],"totalPages":1,"totalRecords":1} ";
            //dynamic data = JObject.Parse(source);
            //Ranorex.Report.Info(data.mailItems.id);
        }

    }
}
