///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

using System.Net.Http;
using System.Web;
using System.Net;
using System.IO;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
namespace project_2
{
	public partial class restfull
	{
		
		private const string URL = "http://localhost:8085/mail";

		private const string DATA = @"{""mailitem"":{""id"":""Name""}}";
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

		public void get_email()
		{
			HttpWebRequest request = (HttpWebRequest)WebRequest.Create(URL);
			request.Method = "GET";
			request.ContentType = "application/json";
			//request.ContentLength = DATA.Length;
			//StreamWriter requestWriter = new StreamWriter(request.GetRequestStream(), System.Text.Encoding.ASCII);
			//requestWriter.Write(DATA);
			//requestWriter.Close();

			try {
				WebResponse webResponse = request.GetResponse();
				Stream webStream = webResponse.GetResponseStream();
				//StreamReader responseReader = new StreamReader(webStream, Encoding.ASCII);
				StreamReader responseReader = new StreamReader(webStream);
				
				string response = responseReader.ReadToEnd();
				Ranorex.Report.Info(response);
				//dynamic data = JObject.Parse(response);
				//Ranorex.Report.Info(data.mailitem.id);
				//string respronse_ok = response.Replace("\"", "\\u022");

				//object empObj = JsonConvert.DeserializeObject(respronse_ok);
				//JObject jobj = JObject.Parse(response);
				
				JObject studentObj = JObject.Parse(response);
				//string name = studentObj["mailItems"]; // Manas
				//var a = studentObj["mailItems"][0];
				var id = studentObj["mailItems"][0]["id"];
				var subject = studentObj["mailItems"][0]["subject"];
				var body = studentObj["mailItems"][0]["body"];
				
				Ranorex.Report.Info("id: " + id.ToString());
				Ranorex.Report.Info("subject: " + subject.ToString());
				Ranorex.Report.Info("body: " + body.ToString());
				// test
				
				responseReader.Close();
			} catch (Exception e) {
				Ranorex.Report.Info("-----------------");
				Ranorex.Report.Info(e.Message);
			}
		}

	}
}
