///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using System.Net.Mail;

namespace project_2
{
    public partial class smtp
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void send_mail()
        {
            try
            {
                MailMessage mail = new MailMessage();
                SmtpClient SmtpServer = new SmtpClient("127.0.0.1");

                mail.From = new MailAddress("from@test.de");
                mail.To.Add("test@test.de");
                mail.Subject = "slurpermail";
                mail.Body = "This is for testing SMTP mail from GMAIL";

                SmtpServer.Port = 25;
                SmtpServer.Credentials = new System.Net.NetworkCredential("", "");
                SmtpServer.EnableSsl = false;

                SmtpServer.Send(mail);
                Ranorex.Report.Info("mail Send");
            }
            catch (Exception ex)
            {
                Ranorex.Report.Info(ex.ToString());
            }
        }

    }
}
